//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DA_WebTimKiemPhimEntities : DbContext
    {
        public DA_WebTimKiemPhimEntities()
            : base("name=DA_WebTimKiemPhimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ghe> Ghes { get; set; }
        public virtual DbSet<Ghe_Ve> Ghe_Ve { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMais { get; set; }
        public virtual DbSet<LichSu> LichSus { get; set; }
        public virtual DbSet<Phim> Phims { get; set; }
        public virtual DbSet<Phim_TheLoai> Phim_TheLoai { get; set; }
        public virtual DbSet<Rap> Raps { get; set; }
        public virtual DbSet<SuatChieu> SuatChieus { get; set; }
        public virtual DbSet<SuatChieu_Phim> SuatChieu_Phim { get; set; }
        public virtual DbSet<SuatChieu_Rap> SuatChieu_Rap { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TheLoai> TheLoais { get; set; }
        public virtual DbSet<Ve> Ves { get; set; }
        public virtual DbSet<YeuThich> YeuThiches { get; set; }
        public virtual DbSet<YeuThich_Phim> YeuThich_Phim { get; set; }
    
        public virtual ObjectResult<DemTKTheoThangNam_Result> DemTKTheoThangNam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DemTKTheoThangNam_Result>("DemTKTheoThangNam");
        }
    
        public virtual int InsertGhe(string maGhe)
        {
            var maGheParameter = maGhe != null ?
                new ObjectParameter("MaGhe", maGhe) :
                new ObjectParameter("MaGhe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertGhe", maGheParameter);
        }
    
        public virtual int InsertHoaDon(string tenTK, Nullable<System.DateTime> ngayDat, Nullable<decimal> tongTien, string trangThai)
        {
            var tenTKParameter = tenTK != null ?
                new ObjectParameter("TenTK", tenTK) :
                new ObjectParameter("TenTK", typeof(string));
    
            var ngayDatParameter = ngayDat.HasValue ?
                new ObjectParameter("NgayDat", ngayDat) :
                new ObjectParameter("NgayDat", typeof(System.DateTime));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(decimal));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertHoaDon", tenTKParameter, ngayDatParameter, tongTienParameter, trangThaiParameter);
        }
    
        public virtual int InsertKhuyenMai(string maKM, string maRap, string tenKM, string hinhAnh, string noiDung, Nullable<System.DateTime> ngayBD, Nullable<System.DateTime> ngayKT)
        {
            var maKMParameter = maKM != null ?
                new ObjectParameter("MaKM", maKM) :
                new ObjectParameter("MaKM", typeof(string));
    
            var maRapParameter = maRap != null ?
                new ObjectParameter("MaRap", maRap) :
                new ObjectParameter("MaRap", typeof(string));
    
            var tenKMParameter = tenKM != null ?
                new ObjectParameter("TenKM", tenKM) :
                new ObjectParameter("TenKM", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var ngayBDParameter = ngayBD.HasValue ?
                new ObjectParameter("NgayBD", ngayBD) :
                new ObjectParameter("NgayBD", typeof(System.DateTime));
    
            var ngayKTParameter = ngayKT.HasValue ?
                new ObjectParameter("NgayKT", ngayKT) :
                new ObjectParameter("NgayKT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertKhuyenMai", maKMParameter, maRapParameter, tenKMParameter, hinhAnhParameter, noiDungParameter, ngayBDParameter, ngayKTParameter);
        }
    
        public virtual int InsertPhim(string maPhim, string tenPhim, string hinhAnh, string daTaTrailer, string thongTinPhim, string noiDung, Nullable<int> thoiLuong, string trangThai, Nullable<System.DateTime> ngayChieu)
        {
            var maPhimParameter = maPhim != null ?
                new ObjectParameter("MaPhim", maPhim) :
                new ObjectParameter("MaPhim", typeof(string));
    
            var tenPhimParameter = tenPhim != null ?
                new ObjectParameter("TenPhim", tenPhim) :
                new ObjectParameter("TenPhim", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var daTaTrailerParameter = daTaTrailer != null ?
                new ObjectParameter("DaTaTrailer", daTaTrailer) :
                new ObjectParameter("DaTaTrailer", typeof(string));
    
            var thongTinPhimParameter = thongTinPhim != null ?
                new ObjectParameter("ThongTinPhim", thongTinPhim) :
                new ObjectParameter("ThongTinPhim", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var thoiLuongParameter = thoiLuong.HasValue ?
                new ObjectParameter("ThoiLuong", thoiLuong) :
                new ObjectParameter("ThoiLuong", typeof(int));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            var ngayChieuParameter = ngayChieu.HasValue ?
                new ObjectParameter("NgayChieu", ngayChieu) :
                new ObjectParameter("NgayChieu", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertPhim", maPhimParameter, tenPhimParameter, hinhAnhParameter, daTaTrailerParameter, thongTinPhimParameter, noiDungParameter, thoiLuongParameter, trangThaiParameter, ngayChieuParameter);
        }
    
        public virtual int InsertPhim_TheLoai(string maTL, string maPhim)
        {
            var maTLParameter = maTL != null ?
                new ObjectParameter("MaTL", maTL) :
                new ObjectParameter("MaTL", typeof(string));
    
            var maPhimParameter = maPhim != null ?
                new ObjectParameter("MaPhim", maPhim) :
                new ObjectParameter("MaPhim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertPhim_TheLoai", maTLParameter, maPhimParameter);
        }
    
        public virtual int InsertRap(string maRap, string tenRap, string diaChi, Nullable<decimal> giaVe, string trangThai)
        {
            var maRapParameter = maRap != null ?
                new ObjectParameter("MaRap", maRap) :
                new ObjectParameter("MaRap", typeof(string));
    
            var tenRapParameter = tenRap != null ?
                new ObjectParameter("TenRap", tenRap) :
                new ObjectParameter("TenRap", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var giaVeParameter = giaVe.HasValue ?
                new ObjectParameter("GiaVe", giaVe) :
                new ObjectParameter("GiaVe", typeof(decimal));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertRap", maRapParameter, tenRapParameter, diaChiParameter, giaVeParameter, trangThaiParameter);
        }
    
        public virtual int insertSuatChieu(string maSC, Nullable<System.TimeSpan> khungGio, string loaiChieu, string trangThai)
        {
            var maSCParameter = maSC != null ?
                new ObjectParameter("MaSC", maSC) :
                new ObjectParameter("MaSC", typeof(string));
    
            var khungGioParameter = khungGio.HasValue ?
                new ObjectParameter("KhungGio", khungGio) :
                new ObjectParameter("KhungGio", typeof(System.TimeSpan));
    
            var loaiChieuParameter = loaiChieu != null ?
                new ObjectParameter("LoaiChieu", loaiChieu) :
                new ObjectParameter("LoaiChieu", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertSuatChieu", maSCParameter, khungGioParameter, loaiChieuParameter, trangThaiParameter);
        }
    
        public virtual int insertSuatChieu_Phim(string maSC, string maPhim)
        {
            var maSCParameter = maSC != null ?
                new ObjectParameter("MaSC", maSC) :
                new ObjectParameter("MaSC", typeof(string));
    
            var maPhimParameter = maPhim != null ?
                new ObjectParameter("MaPhim", maPhim) :
                new ObjectParameter("MaPhim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertSuatChieu_Phim", maSCParameter, maPhimParameter);
        }
    
        public virtual int insertSuatChieu_Rap(string maSC, string maRap, Nullable<System.DateTime> ngayChieu)
        {
            var maSCParameter = maSC != null ?
                new ObjectParameter("MaSC", maSC) :
                new ObjectParameter("MaSC", typeof(string));
    
            var maRapParameter = maRap != null ?
                new ObjectParameter("MaRap", maRap) :
                new ObjectParameter("MaRap", typeof(string));
    
            var ngayChieuParameter = ngayChieu.HasValue ?
                new ObjectParameter("NgayChieu", ngayChieu) :
                new ObjectParameter("NgayChieu", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertSuatChieu_Rap", maSCParameter, maRapParameter, ngayChieuParameter);
        }
    
        public virtual int InsertTheLoai(string maTL, string tenTL)
        {
            var maTLParameter = maTL != null ?
                new ObjectParameter("MaTL", maTL) :
                new ObjectParameter("MaTL", typeof(string));
    
            var tenTLParameter = tenTL != null ?
                new ObjectParameter("TenTL", tenTL) :
                new ObjectParameter("TenTL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTheLoai", maTLParameter, tenTLParameter);
        }
    
        public virtual int InsertTK(string tenTK, string matKhau, string hoVaTen, string hinhAnh, string diaChi, string soDienThoai, string email, string loaiTK, Nullable<System.DateTime> ngayDK, string trangThai)
        {
            var tenTKParameter = tenTK != null ?
                new ObjectParameter("TenTK", tenTK) :
                new ObjectParameter("TenTK", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("HoVaTen", hoVaTen) :
                new ObjectParameter("HoVaTen", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var loaiTKParameter = loaiTK != null ?
                new ObjectParameter("LoaiTK", loaiTK) :
                new ObjectParameter("LoaiTK", typeof(string));
    
            var ngayDKParameter = ngayDK.HasValue ?
                new ObjectParameter("NgayDK", ngayDK) :
                new ObjectParameter("NgayDK", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTK", tenTKParameter, matKhauParameter, hoVaTenParameter, hinhAnhParameter, diaChiParameter, soDienThoaiParameter, emailParameter, loaiTKParameter, ngayDKParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<ThongKeDoanhThuTheoThang_Result> ThongKeDoanhThuTheoThang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeDoanhThuTheoThang_Result>("ThongKeDoanhThuTheoThang");
        }
    }
}
