//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ghe_Ve
    {
        public int ID { get; set; }
        public string MaGhe { get; set; }
        public Nullable<int> MaVe { get; set; }
    
        public virtual Ghe Ghe { get; set; }
        public virtual Ve Ve { get; set; }
    }
}
