//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHD { get; set; }
        public Nullable<int> MaVe { get; set; }
        public string TenTK { get; set; }
        public System.DateTime NgayDat { get; set; }
        public decimal TongTien { get; set; }
        public string TrangThai { get; set; }
    
        public virtual Ve Ve { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
