//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phim()
        {
            this.Phim_TheLoai = new HashSet<Phim_TheLoai>();
            this.SuatChieu_Phim = new HashSet<SuatChieu_Phim>();
            this.Ves = new HashSet<Ve>();
            this.YeuThich_Phim = new HashSet<YeuThich_Phim>();
        }
    
        public string MaPhim { get; set; }
        public string TenPhim { get; set; }
        public string HinhAnh { get; set; }
        public string DaTaTrailer { get; set; }
        public string ThongTinPhim { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> ThoiLuong { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime NgayChieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phim_TheLoai> Phim_TheLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuatChieu_Phim> SuatChieu_Phim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuThich_Phim> YeuThich_Phim { get; set; }
    }
}
