//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuatChieu_Phim
    {
        public int ID { get; set; }
        public string MaSC { get; set; }
        public string MaPhim { get; set; }
    
        public virtual Phim Phim { get; set; }
        public virtual SuatChieu SuatChieu { get; set; }
    }
}
