//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ve()
        {
            this.Ghe_Ve = new HashSet<Ghe_Ve>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int MaVe { get; set; }
        public string MaSC { get; set; }
        public string MaPhim { get; set; }
        public string MaRap { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string TrangThaiVe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ghe_Ve> Ghe_Ve { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual Phim Phim { get; set; }
        public virtual Rap Rap { get; set; }
        public virtual SuatChieu SuatChieu { get; set; }
    }
}
